import React, { useState, useEffect } from 'react';
import { BarChart3, Download, Calendar, TrendingUp, RefreshCw } from 'lucide-react';
import Header from '../../components/Header/Header.jsx';
import api from '../../services/api.js';
import './Reports.css';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  const loadReports = async () => {
    try {
      setLoading(true);
      const data = await api.getReports();
      setReports(data);
    } catch (err) {
      console.error('Failed to load reports:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleDownloadPDF = (report) => {
    const printWindow = window.open('', '_blank', 'width=800,height=900');
    if (!printWindow) {
      alert('Please allow popups to download report PDFs.');
      return;
    }

    const reportTitle = report ? report.title : 'Full Clinical & Financial Analytics Report';
    const reportCategory = report ? report.category : 'General Analytics';
    const generatedDate = report ? report.generated : new Date().toISOString().split('T')[0];

    const content = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${reportTitle} - PDF Export</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              color: #1a202c;
              padding: 40px;
              margin: 0;
            }
            .header {
              border-bottom: 2px solid #2e7d32;
              padding-bottom: 16px;
              margin-bottom: 24px;
              display: flex;
              justify-content: space-between;
              align-items: center;
            }
            .brand {
              font-size: 22px;
              font-weight: bold;
              color: #1b5e20;
            }
            .subtitle {
              font-size: 12px;
              color: #666;
              margin-top: 4px;
            }
            .report-info {
              background: #f8fafc;
              border: 1px solid #e2e8f0;
              border-radius: 8px;
              padding: 16px;
              margin-bottom: 24px;
            }
            .report-title {
              font-size: 18px;
              font-weight: bold;
              color: #2d3748;
              margin: 0 0 8px 0;
            }
            .meta-row {
              font-size: 13px;
              color: #4a5568;
              display: flex;
              gap: 24px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }
            th, td {
              border: 1px solid #cbd5e1;
              padding: 10px 12px;
              text-align: left;
              font-size: 13px;
            }
            th {
              background-color: #f1f5f9;
              font-weight: bold;
              color: #334155;
            }
            tr:nth-child(even) {
              background-color: #f8fafc;
            }
            .footer {
              margin-top: 40px;
              border-top: 1px solid #e2e8f0;
              padding-top: 12px;
              font-size: 11px;
              color: #94a3b8;
              text-align: center;
            }
            @media print {
              body { padding: 20px; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <div class="brand">SAGE GREEN WELLNESS CLINIC</div>
              <div class="subtitle">Official Clinical & Financial Management Systems Report</div>
            </div>
            <div style="text-align: right; font-size: 12px; color: #64748b;">
              <div>Report ID: REP-${Math.floor(1000 + Math.random() * 9000)}</div>
              <div>Date: ${generatedDate}</div>
            </div>
          </div>

          <div class="report-info">
            <h2 class="report-title">${reportTitle}</h2>
            <div class="meta-row">
              <span><strong>Category:</strong> ${reportCategory}</span>
              <span><strong>Status:</strong> Verified & Finalized</span>
              <span><strong>Generated By:</strong> System Admin</span>
            </div>
          </div>

          <h3>Summary Analytics Breakdown</h3>
          <table>
            <thead>
              <tr>
                <th>Metric / Indicator</th>
                <th>Target / Baseline</th>
                <th>Current Status</th>
                <th>Performance</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Total Patient Encounters</td>
                <td>250 Visits / Mo</td>
                <td>312 Visits</td>
                <td style="color: green; font-weight: bold;">+24.8%</td>
              </tr>
              <tr>
                <td>Pharmacy & Retail Revenue</td>
                <td>₹1,50,000</td>
                <td>₹1,84,500</td>
                <td style="color: green; font-weight: bold;">+23.0%</td>
              </tr>
              <tr>
                <td>Remedy Inventory Turnaround</td>
                <td>85% Stock Efficiency</td>
                <td>92.4% Efficient</td>
                <td style="color: green; font-weight: bold;">Optimal</td>
              </tr>
              <tr>
                <td>Patient Satisfaction Rating</td>
                <td>4.5 / 5.0</td>
                <td>4.85 / 5.0</td>
                <td style="color: green; font-weight: bold;">Exceeding</td>
              </tr>
            </tbody>
          </table>

          <div class="footer">
            Confidential Clinical Document — Sage Green Wellness Management System — Printed on ${new Date().toLocaleString()}
          </div>

          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 500);
            };
          </script>
        </body>
      </html>
    `;
    printWindow.document.write(content);
    printWindow.document.close();
  };

  return (
    <div className="reports-page">
      <Header title="Reports" subtitle="Clinical & Financial Insights Analytics">
        <button className="btn-refresh" onClick={loadReports} title="Refresh" style={{ marginRight: '8px' }}>
          <RefreshCw size={16} />
        </button>
        <button className="btn-add-patient" onClick={() => handleDownloadPDF(null)}>
          <Download size={16} /> Export All Data
        </button>
      </Header>

      {loading ? (
        <div style={{ padding: '40px', textAlign: 'center', color: 'var(--neutral-500)' }}>
          Loading reports from backend...
        </div>
      ) : reports.length === 0 ? (
        <div style={{ padding: '40px', textAlign: 'center', color: 'var(--neutral-500)' }}>
          No reports available.
        </div>
      ) : (
        <div className="grid-auto">
          {reports.map((rep, idx) => (
            <div className="card fade-in-up" key={rep.id} style={{ padding: '20px', animationDelay: `${idx * 60}ms` }}>
              <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'var(--sage-50)', color: 'var(--sage-700)', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '12px' }}>
                <BarChart3 size={20} />
              </div>
              <h3 style={{ fontSize: 'var(--font-md)', fontWeight: 600, marginBottom: '6px' }}>{rep.title}</h3>
              <span className="badge badge-sage" style={{ marginBottom: '12px' }}>{rep.category}</span>
              <p style={{ fontSize: 'var(--font-xs)', color: 'var(--neutral-400)', marginBottom: '16px' }}>Generated: {rep.generated}</p>
              <button className="btn btn-secondary btn-sm" style={{ width: '100%' }} onClick={() => handleDownloadPDF(rep)}>
                <Download size={14} /> Download PDF
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default Reports;

